/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PokerJava;

import java.util.*;

public class App {
    public static void main(String[] args) {
        List<Card> cards = Card.fromString(args[0]);
        Combo combo = new Combo(cards);

        System.out.println(combo.best());
    }
}
