// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
package PokerJava;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.junit.Assert.assertEquals;

public class AppTest {
    @Test public void testFlushCombo() {
        String[] args = {"As-Ks-3s-2s-5s"};
        assertEquals("Flush", App.combo(args));
    }

    @Test public void testPairCombo() {
        String[] args = {"As-Ad-3s-2s-5s"};
        assertEquals("Pair", App.combo(args));
    }

    @Test public void testAirCombo() {
        String[] args = {"As-7d-3s-2s-5s"};
        assertEquals("Air", App.combo(args));
    }
}
